[package]
name = "insightface"
version = "0.0.2"
edition = "2021"
license = "MIT"
homepage = "https://pwa.ir"
repository = "https://github.com/xclud/rust_insightface"
documentation = "https://docs.rs/crate/insightface"
description = "Crate to work with Insightface's Face Detection and Face Swap models."
categories = ["algorithms", "science", "computer-vision"]
keywords = ["insightface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ort = {git="https://github.com/pykeio/ort/", default-features = false, features = ["std", "ndarray",  "download-binaries", "tls-rustls"] }
ndarray = "0.16"
image = "^0.24.9"
aikit = "^0.0.2"
nalgebra = "^0.32.4"